### ISSUE TITLE
Bug: enum34 conditional requirement for poetry

### ISSUE THREAD

**Issue by tpinniger** [manrajgrover/py-spinners#27]
## Description
We have migrated to poetry for our python 3.6+ development.  It picks up the enum34 conditional include as a dependency unless the format of setup.py is changed.

### System settings

- Operating System: aws linux
- Terminal in use: bash
- Python version: 3.6+
- halo = "^0.0.28" is bringing in py-spinners

### Error
Traceback (most recent call last):
File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.7/site-packages/pip/__main__.py", line 16,
in <module>
from pip._internal import main as _main  # isort:skip # noqa
File "/usr/local/lib/python3.7/site-packages/pip/_internal/__init__.py",
line 4, in <module>
import locale
File "/usr/local/lib/python3.7/locale.py", line 16, in <module>
import re
File "/usr/local/lib/python3.7/re.py", line 143, in <module>
class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

**Comment by manrajgrover** [comment]
Marking this as solved
